import { afterAll, afterEach, beforeAll, jest } from '@jest/globals';
import { rm } from 'fs/promises';
import path from 'path';

beforeAll(() => {
  process.env.DATABASE_URL ??=
    'postgresql://test_user:test_password@localhost:5432/snap_or_slap_test';

  process.env.JWT_ACCESS_SECRET ??= 'test-access-secret';
  process.env.JWT_REFRESH_SECRET ??= 'test-refresh-secret';
  process.env.CRON_SECRET ??= 'test-cron-secret';

  process.env.APP_BASE_URL ??= 'http://localhost:3000';

  /**
   * Used by proofUploadService.ts.
   * In production, this may point to Railway/custom public URL.
   * In test, keep it deterministic.
   */
  process.env.UPLOAD_PUBLIC_BASE_URL ??= 'http://localhost:3000';
  process.env.NEXT_PUBLIC_UPLOAD_PUBLIC_BASE_URL ??= 'http://localhost:3000';
});

afterEach(() => {
  jest.clearAllMocks();
});

/**
 * Clean temporary proof images generated by tests.
 * Safe because proofUploadService writes to:
 * public/uploads/checkins/...
 */
afterAll(async () => {
  const uploadDir = path.join(process.cwd(), 'public', 'uploads');

  await rm(uploadDir, {
    recursive: true,
    force: true,
  }).catch(() => {
    // Ignore cleanup errors in test environment.
  });
});